baseURL = "https://bsmaple.github.io/"
languageCode = "zh-cn"
title = "BSMaple çš„æŠ€æœ¯åšå®¢"
theme = "PaperMod"

enableRobotsTXT = true

[author]
  name = "BSMaple"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  author = "BSMaple"

  [params.homeInfoParams]
    Title = "Hi, æˆ‘æ˜¯ BSMaple ğŸ‘‹"
    Content = "è¿™é‡Œè®°å½•æˆ‘çš„çš„å­¦ä¹ ä¸é¡¹ç›®å¤ç›˜ã€‚"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
